<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {onMounted,reactive,ref} from 'vue';import {request} from '../api'
const rows=ref([]),dashboard=ref(null),gates=reactive({}),error=ref('')
const form=reactive({appCode:'APP-SALES',versionNo:'1.0.'+Date.now(),name:'销售运营应用',pageCount:8,workflowCount:3,validationErrors:0,unresolvedDependencies:0,testCoverage:85,criticalSecurityFindings:0,ownerAssigned:true,permissionsReviewed:true,rollbackSnapshotReady:true,packageDigest:'sha256:'+'a'.repeat(64)})
async function load(){try{[rows.value,dashboard.value]=await Promise.all([request('/api/lowcode/applications'),request('/api/lowcode/applications/dashboard')])}catch(e){error.value=e.message}}
async function create(){try{await request('/api/lowcode/applications',{method:'POST',body:JSON.stringify(form)});form.versionNo='1.0.'+Date.now();await load()}catch(e){error.value=e.message}}
async function gate(i){try{gates[i.id]=await request(`/api/lowcode/applications/${i.id}/publish-gate`)}catch(e){error.value=e.message}}
async function act(i,a){if(!confirm('确认'+a+' '+i.appCode+' / '+i.versionNo+'？'))return;try{if(a==='晋级测试')await request(`/api/lowcode/applications/${i.id}/promote-test`,{method:'POST',body:JSON.stringify({packageDigest:i.packageDigest})});if(a==='提交验收')await request(`/api/lowcode/applications/${i.id}/submit`,{method:'POST'});if(a==='发布')await request(`/api/admin/lowcode/applications/${i.id}/publish?remark=${encodeURIComponent('业务与安全验收通过')}`,{method:'POST'});if(a==='回退')await request(`/api/admin/lowcode/applications/${i.id}/rollback?reason=${encodeURIComponent('生产运行异常')}`,{method:'POST'});await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="head"><div><span>APPLICATION LIFECYCLE</span><h3>低代码应用发布中心</h3><p>应用版本、页面与流程规模、自动化覆盖率、安全与权限门禁、发布及可审计回退。</p></div><b>版本化交付</b></section><p v-if="error" class="error" @click="error=''">{{error}} ×</p>
<section v-if="dashboard" class="metrics"><article><span>应用版本</span><b>{{dashboard.total}}</b></article><article><span>草稿</span><b>{{dashboard.draft}}</b></article><article><span>已发布</span><b>{{dashboard.published}}</b></article><article><span>门禁阻断</span><b>{{dashboard.blocked}}</b></article></section>
<form class="card form" @submit.prevent="create"><label>应用编码<input v-model="form.appCode" required></label><label>版本<input v-model="form.versionNo" required></label><label class="wide">应用名称<input v-model="form.name" required></label><label class="wide">制品摘要<input v-model="form.packageDigest" required></label><label>页面数<input v-model.number="form.pageCount" type="number" min="1"></label><label>流程数<input v-model.number="form.workflowCount" type="number" min="0"></label><label>测试覆盖率<input v-model.number="form.testCoverage" type="number" min="0" max="100"></label><label>校验错误<input v-model.number="form.validationErrors" type="number" min="0"></label><label>未解决依赖<input v-model.number="form.unresolvedDependencies" type="number" min="0"></label><label>严重安全项<input v-model.number="form.criticalSecurityFindings" type="number" min="0"></label><label class="check"><input v-model="form.ownerAssigned" type="checkbox">负责人已指定</label><label class="check"><input v-model="form.permissionsReviewed" type="checkbox">权限已复核</label><label class="check"><input v-model="form.rollbackSnapshotReady" type="checkbox">回滚快照就绪</label><button>创建应用版本</button></form>
<section class="card table"><table><thead><tr><th>应用 / 版本</th><th>环境 / 制品</th><th>规模</th><th>质量</th><th>状态</th><th>门禁</th><th>操作</th></tr></thead><tbody><tr v-for="i in rows"><td><b>{{i.name}}</b><small>{{i.appCode}} / {{i.versionNo}}</small></td><td>{{i.promotedEnvironment}}<small>{{i.packageDigest.slice(0,20)}}…</small></td><td>{{i.pageCount}} 页面<small>{{i.workflowCount}} 流程</small></td><td>覆盖率 {{i.testCoverage}}%<small>错误 {{i.validationErrors}} · 安全 {{i.criticalSecurityFindings}}</small></td><td>{{i.state}}</td><td><button class="text" @click="gate(i)">检查</button><small v-if="gates[i.id]" :class="{blocked:gates[i.id].decision==='BLOCKED'}">{{gates[i.id].decision}}</small></td><td><button v-if="i.state==='DRAFT'&&i.promotedEnvironment==='DEV'" class="text" @click="act(i,'晋级测试')">晋级测试</button><button v-if="i.state==='DRAFT'&&i.promotedEnvironment==='TEST'" class="text" @click="act(i,'提交验收')">提交</button><button v-if="i.state==='PENDING_REVIEW'" class="text" @click="act(i,'发布')">发布</button><button v-if="i.state==='PUBLISHED'" class="text danger" @click="act(i,'回退')">回退</button></td></tr></tbody></table></section></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:end;background:#fff;border:1px solid #dce2df;padding:24px 28px;margin-bottom:16px}.head span{font-size:11px;letter-spacing:.16em;color:#b47c2f}.head h3{font-size:24px;margin:5px 0}.head p{margin:0;color:#68777c}.head>b{color:#235a74}.metrics{margin-bottom:16px}.card{background:#fff;border:1px solid #dce2df;padding:20px;margin-bottom:16px}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.form label{display:grid;gap:5px;font-size:12px;color:#68777c}.form input{border:1px solid #ccd6d2;padding:9px}.form .wide{grid-column:span 2}.check{display:flex!important;align-items:center;gap:7px}.check input{width:17px}.form button{border:0;background:#235a74;color:#fff;font-weight:700}.table{padding:0;overflow:auto}.table table{min-width:900px}td small{display:block;color:#68777c}.text{border:0;background:transparent;color:#235a74;padding:4px}.danger,.blocked,.error{color:#a03f38}@media(max-width:900px){.form{grid-template-columns:1fr}.form .wide{grid-column:auto}}</style>
